CREATE TABLE nw2_mst(
nwid int,
nw1_id int,
sortnum int,
dupflg int,
nwnm varchar(100) NOT NULL,
nwtext varchar(300),
addr1 int,
addr2 int,
addr3 int,
addr4 int,
mask int,
updateflg int,
delflg int,
create_userid  varchar(20) NOT NULL,
create_usernm  varchar(100) NOT NULL,
create_deptid int,
create_deptnm varchar(100),
create_date datetime,
update_userid  varchar(20) NOT NULL,
update_usernm  varchar(100) NOT NULL,
update_deptid int,
update_deptnm varchar(100),
update_date datetime,
PRIMARY KEY(nwid)
);
